export const POST_UPDATE = 'POST_UPDATE';
export const POST_PERSIST = 'POST_PERSIST';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_FAILURE = 'POSTS_FETCH_FAILURE';
